language: "node_js"
node_js:
  - "10"
  - "8"
  - "6"


before_install:
  - "npm install istanbul@0.4.x -g"
  - "npm install coveralls@2.x.x -g"

script:
  - "make test-cov"

after_success:
  - "make report-cov"
